// @generated by sophia-policy-protocol-gen; do not edit.
// Source: protocol/sophia-wm-v1.kdl

use super::cursor::{Cursor, push_i32, push_u16, push_u32, push_u64};
use super::frame::{decode_frame, encode_frame};
use super::types::{IpcCodecError, IpcMessageKind};
use crate::TransactionId;

pub const SOPHIA_WM_INTERFACE_MAJOR: u16 = 1;
pub const SOPHIA_WM_INTERFACE_REVISION: u16 = 1;
pub const SOPHIA_WM_MAX_OUTPUTS: usize = 16;
pub const SOPHIA_WM_MAX_SURFACES: usize = 1024;
pub const SOPHIA_WM_MAX_BINDINGS: usize = 256;

pub const SOPHIA_WM_CAPABILITY_BINDINGS: u64 = 1 << 0;
pub const SOPHIA_WM_CAPABILITY_ACTIONS: u64 = 1 << 1;
pub const SOPHIA_WM_CAPABILITY_MULTI_OUTPUT: u64 = 1 << 2;

pub const SOPHIA_WM_OUTCOME_COMMITTED: u16 = 1;
pub const SOPHIA_WM_OUTCOME_REJECTED_STALE: u16 = 2;
pub const SOPHIA_WM_OUTCOME_REJECTED_INVALID: u16 = 3;
pub const SOPHIA_WM_OUTCOME_TIMED_OUT: u16 = 4;
pub const SOPHIA_WM_OUTCOME_DISCONNECTED: u16 = 5;

pub const SNAPSHOT_OUTPUT_RECORD_KIND: u16 = 1;
pub const SNAPSHOT_OUTPUT_RECORD_SIZE: usize = 40;
pub const SNAPSHOT_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotOutputRecord {
    pub output: u64,
    pub generation: u64,
    pub focus_index: u32,
    pub focus_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

pub fn encode_wm_v1_snapshot_output_records(
    records: &[WmV1SnapshotOutputRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 16 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 40);
    for record in records {
        push_u64(&mut data, record.output);
        push_u64(&mut data, record.generation);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotOutputRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(IpcCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(40)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let generation = cursor.u64()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        records.push(WmV1SnapshotOutputRecord {
            output,
            generation,
            focus_index,
            focus_generation,
            x,
            y,
            width,
            height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_SURFACE_RECORD_KIND: u16 = 2;
pub const SNAPSHOT_SURFACE_RECORD_SIZE: usize = 68;
pub const SNAPSHOT_SURFACE_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotSurfaceRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub current_output: u64,
    pub capability_bits: u16,
    pub transient_index: u32,
    pub transient_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub min_width: i32,
    pub min_height: i32,
    pub max_width: i32,
    pub max_height: i32,
}

pub fn encode_wm_v1_snapshot_surface_records(
    records: &[WmV1SnapshotSurfaceRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 1024 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 68);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_u64(&mut data, record.current_output);
        push_u16(&mut data, record.capability_bits);
        push_u16(&mut data, 0);
        push_u32(&mut data, record.transient_index);
        push_u32(&mut data, record.transient_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.min_width);
        push_i32(&mut data, record.min_height);
        push_i32(&mut data, record.max_width);
        push_i32(&mut data, record.max_height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_surface_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotSurfaceRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(IpcCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(68)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let current_output = cursor.u64()?;
        let capability_bits = cursor.u16()?;
        let reserved = cursor.u16()?;
        if reserved != 0 {
            return Err(IpcCodecError::ReservedNonZero(reserved as u32));
        }
        let transient_index = cursor.u32()?;
        let transient_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let min_width = cursor.i32()?;
        let min_height = cursor.i32()?;
        let max_width = cursor.i32()?;
        let max_height = cursor.i32()?;
        records.push(WmV1SnapshotSurfaceRecord {
            surface_index,
            surface_generation,
            state_generation,
            current_output,
            capability_bits,
            transient_index,
            transient_generation,
            x,
            y,
            width,
            height,
            min_width,
            min_height,
            max_width,
            max_height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_BINDING_RECORD_KIND: u16 = 3;
pub const SNAPSHOT_BINDING_RECORD_SIZE: usize = 16;
pub const SNAPSHOT_BINDING_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotBindingRecord {
    pub action: u64,
    pub keycode: u32,
    pub modifier_bits: u32,
}

pub fn encode_wm_v1_snapshot_binding_records(
    records: &[WmV1SnapshotBindingRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 256 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 16);
    for record in records {
        push_u64(&mut data, record.action);
        push_u32(&mut data, record.keycode);
        push_u32(&mut data, record.modifier_bits);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_binding_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotBindingRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(IpcCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(16)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let action = cursor.u64()?;
        let keycode = cursor.u32()?;
        let modifier_bits = cursor.u32()?;
        records.push(WmV1SnapshotBindingRecord {
            action,
            keycode,
            modifier_bits,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_OUTPUT_RECORD_KIND: u16 = 1;
pub const PROJECTION_OUTPUT_RECORD_SIZE: usize = 24;
pub const PROJECTION_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutputRecord {
    pub output: u64,
    pub placement_count: u32,
    pub focus_index: u32,
    pub focus_generation: u32,
}

pub fn encode_wm_v1_projection_output_records(
    records: &[WmV1ProjectionOutputRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 16 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 24);
    for record in records {
        push_u64(&mut data, record.output);
        push_u32(&mut data, record.placement_count);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_u32(&mut data, 0);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionOutputRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(IpcCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(24)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let placement_count = cursor.u32()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let reserved = cursor.u32()?;
        if reserved != 0 {
            return Err(IpcCodecError::ReservedNonZero(reserved as u32));
        }
        records.push(WmV1ProjectionOutputRecord {
            output,
            placement_count,
            focus_index,
            focus_generation,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_PLACEMENT_RECORD_KIND: u16 = 2;
pub const PROJECTION_PLACEMENT_RECORD_SIZE: usize = 60;
pub const PROJECTION_PLACEMENT_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionPlacementRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub requested_width: i32,
    pub requested_height: i32,
    pub crop_x: i32,
    pub crop_y: i32,
    pub crop_width: i32,
    pub crop_height: i32,
    pub transform: u16,
}

pub fn encode_wm_v1_projection_placement_records(
    records: &[WmV1ProjectionPlacementRecord],
) -> Result<Vec<u8>, IpcCodecError> {
    if records.len() > 1024 {
        return Err(IpcCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 60);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.requested_width);
        push_i32(&mut data, record.requested_height);
        push_i32(&mut data, record.crop_x);
        push_i32(&mut data, record.crop_y);
        push_i32(&mut data, record.crop_width);
        push_i32(&mut data, record.crop_height);
        push_u16(&mut data, record.transform);
        push_u16(&mut data, 0);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_placement_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionPlacementRecord>, IpcCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(IpcCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(60)
        .ok_or(IpcCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(IpcCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(IpcCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let requested_width = cursor.i32()?;
        let requested_height = cursor.i32()?;
        let crop_x = cursor.i32()?;
        let crop_y = cursor.i32()?;
        let crop_width = cursor.i32()?;
        let crop_height = cursor.i32()?;
        let transform = cursor.u16()?;
        let reserved = cursor.u16()?;
        if reserved != 0 {
            return Err(IpcCodecError::ReservedNonZero(reserved as u32));
        }
        records.push(WmV1ProjectionPlacementRecord {
            surface_index,
            surface_generation,
            state_generation,
            x,
            y,
            width,
            height,
            requested_width,
            requested_height,
            crop_x,
            crop_y,
            crop_width,
            crop_height,
            transform,
        });
    }
    cursor.finish()?;
    Ok(records)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ClientHello {
    pub minimum_revision: u16,
    pub maximum_revision: u16,
    pub capabilities: u64,
}

pub fn encode_wm_v1_client_hello_frame(
    message: &WmV1ClientHello,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.minimum_revision);
    push_u16(&mut payload, message.maximum_revision);
    push_u64(&mut payload, message.capabilities);
    encode_frame(
        IpcMessageKind::WmV1ClientHello,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_client_hello_frame(frame: &[u8]) -> Result<WmV1ClientHello, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ClientHello {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let minimum_revision = cursor.u16()?;
    let maximum_revision = cursor.u16()?;
    let capabilities = cursor.u64()?;
    cursor.finish()?;
    let message = WmV1ClientHello {
        minimum_revision,
        maximum_revision,
        capabilities,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ServerWelcome {
    pub selected_revision: u16,
    pub capabilities: u64,
    pub connection_epoch: u64,
    pub max_outputs: u16,
    pub max_bindings: u16,
    pub max_surfaces: u32,
    pub max_chunk_bytes: u32,
}

pub fn encode_wm_v1_server_welcome_frame(
    message: &WmV1ServerWelcome,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.selected_revision);
    push_u16(&mut payload, 0);
    push_u64(&mut payload, message.capabilities);
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.max_outputs);
    push_u16(&mut payload, message.max_bindings);
    push_u32(&mut payload, message.max_surfaces);
    push_u32(&mut payload, message.max_chunk_bytes);
    encode_frame(
        IpcMessageKind::WmV1ServerWelcome,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_server_welcome_frame(frame: &[u8]) -> Result<WmV1ServerWelcome, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ServerWelcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let selected_revision = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let capabilities = cursor.u64()?;
    let connection_epoch = cursor.u64()?;
    let max_outputs = cursor.u16()?;
    let max_bindings = cursor.u16()?;
    let max_surfaces = cursor.u32()?;
    let max_chunk_bytes = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1ServerWelcome {
        selected_revision,
        capabilities,
        connection_epoch,
        max_outputs,
        max_bindings,
        max_surfaces,
        max_chunk_bytes,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotBegin {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub surface_count: u32,
    pub binding_count: u16,
}

pub fn encode_wm_v1_snapshot_begin_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.surface_count);
    push_u16(&mut payload, message.binding_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1SnapshotBegin, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let surface_count = cursor.u32()?;
    let binding_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SnapshotBegin {
        connection_epoch,
        scene_generation,
        chunk_count,
        output_count,
        surface_count,
        binding_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_snapshot_chunk_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1SnapshotChunk, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1SnapshotChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotEnd {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_snapshot_end_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1SnapshotEnd, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SnapshotEnd {
        connection_epoch,
        scene_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_projection_request_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(IpcMessageKind::WmV1ProjectionRequest, transaction, &payload)
}

pub fn decode_wm_v1_projection_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(28);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionRequest {
        connection_epoch,
        request_id,
        scene_generation,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionBegin {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub placement_count: u32,
}

pub fn encode_wm_v1_projection_begin_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.placement_count);
    encode_frame(IpcMessageKind::WmV1ProjectionBegin, transaction, &payload)
}

pub fn decode_wm_v1_projection_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let placement_count = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1ProjectionBegin {
        connection_epoch,
        request_id,
        base_generation,
        chunk_count,
        output_count,
        placement_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_projection_chunk_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1ProjectionChunk, transaction, &payload)
}

pub fn decode_wm_v1_projection_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionEnd {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_projection_end_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionEnd, transaction, &payload)
}

pub fn decode_wm_v1_projection_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionEnd {
        connection_epoch,
        request_id,
        base_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutcome {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_projection_outcome_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionOutcome, transaction, &payload)
}

pub fn decode_wm_v1_projection_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionOutcome {
        connection_epoch,
        request_id,
        scene_generation,
        outcome,
    };
    Ok((header.transaction, message))
}
