use std::fmt::Write as _;

use sophia_protocol::*;

fn main() {
    let mode = std::env::args().nth(1).unwrap_or_default();
    let valid = valid_frames();
    match mode.as_str() {
        "--valid" => {
            println!("# @generated by shell_v1_corpus; do not edit.");
            println!("# name|transaction|frame-hex");
            for (name, transaction, frame) in valid {
                println!("{name}|{}|{}", transaction.raw(), hex(&frame));
            }
        }
        "--malformed" => {
            println!("# @generated by shell_v1_corpus; do not edit.");
            println!("# case|decoder|expected-error|frame-hex");
            for (case, decoder, expected, frame) in malformed_frames(&valid) {
                println!("{case}|{decoder}|{expected}|{}", hex(&frame));
            }
        }
        _ => {
            eprintln!("usage: shell_v1_corpus --valid|--malformed");
            std::process::exit(2);
        }
    }
}

fn valid_frames() -> Vec<(&'static str, TransactionId, Vec<u8>)> {
    let transaction = TransactionId::from_raw(0x0102_0304_0506_0708);
    let hello = encode_shell_v1_client_hello_frame(ShellV1ClientHello {
        minimum_revision: 1,
        maximum_revision: 1,
        required_capabilities: SOPHIA_SHELL_CAPABILITY_DESCRIPTOR_SWITCHER,
    })
    .unwrap();
    let welcome = encode_shell_v1_server_welcome_frame(ShellV1ServerWelcome {
        selected_revision: 1,
        connection_epoch: 5,
        capabilities: SOPHIA_SHELL_CAPABILITY_DESCRIPTOR_SWITCHER,
        max_descriptors: SOPHIA_SHELL_MAX_DESCRIPTORS as u16,
        max_label_bytes: MAX_CHROME_LABEL_LEN as u16,
        max_pending_activations: SOPHIA_SHELL_MAX_PENDING_ACTIVATIONS as u16,
    })
    .unwrap();
    let snapshot = encode_shell_v1_descriptor_snapshot_frame(
        transaction,
        &ShellV1DescriptorSnapshot {
            connection_epoch: 5,
            snapshot_generation: 6,
            output: OutputId::from_raw(7),
            output_generation: 8,
            broker_epoch: 3,
            broker_revocation_epoch: 4,
            descriptors: vec![ShellV1Descriptor {
                slot: 2,
                generation: 10,
                label: Some(DisplayLabel {
                    text: "Browser".into(),
                    redacted: true,
                }),
                trust_level: TrustLevel::Isolated,
                attention: AttentionState::Notice,
                action: action(),
            }],
        },
    )
    .unwrap();
    let candidate = encode_shell_v1_candidate_frame(
        transaction,
        &ShellV1Candidate {
            connection_epoch: 5,
            snapshot_generation: 6,
            candidate_generation: 1,
            output: OutputId::from_raw(7),
            visible: true,
            selected_slot: Some(2),
            reservation: None,
            entries: vec![ShellV1CandidateEntry {
                slot: 2,
                generation: 10,
            }],
        },
    )
    .unwrap();
    let candidate_reserved = encode_shell_v1_candidate_frame(
        transaction,
        &ShellV1Candidate {
            connection_epoch: 5,
            snapshot_generation: 6,
            candidate_generation: 2,
            output: OutputId::from_raw(7),
            visible: true,
            selected_slot: Some(2),
            reservation: Some(ShellV1WorkAreaReservation {
                edge: ShellV1ReservationEdge::Bottom,
                thickness_px: 28,
            }),
            entries: vec![ShellV1CandidateEntry {
                slot: 2,
                generation: 10,
            }],
        },
    )
    .unwrap();
    let candidate_hidden = encode_shell_v1_candidate_frame(
        transaction,
        &ShellV1Candidate {
            connection_epoch: 5,
            snapshot_generation: 6,
            candidate_generation: 3,
            output: OutputId::from_raw(7),
            visible: false,
            selected_slot: None,
            reservation: None,
            entries: Vec::new(),
        },
    )
    .unwrap();
    let outcome = encode_shell_v1_candidate_outcome_frame(
        transaction,
        ShellV1CandidateOutcome {
            connection_epoch: 5,
            candidate_generation: 1,
            presentation_epoch: 12,
            kind: ShellV1CandidateOutcomeKind::Presented,
        },
    )
    .unwrap();
    let activation = encode_shell_v1_activation_frame(
        transaction,
        ShellV1Activation {
            connection_epoch: 5,
            candidate_generation: 1,
            presentation_epoch: 12,
            activation: 13,
            action: action(),
        },
    )
    .unwrap();
    let ack = encode_shell_v1_activation_ack_frame(
        transaction,
        ShellV1ActivationAck {
            connection_epoch: 5,
            activation: 13,
            disposition: ShellV1ActivationDisposition::Consumed,
        },
    )
    .unwrap();
    let unlabeled_snapshot = encode_shell_v1_descriptor_snapshot_frame(
        transaction,
        &ShellV1DescriptorSnapshot {
            connection_epoch: 5,
            snapshot_generation: 6,
            output: OutputId::from_raw(7),
            output_generation: 8,
            broker_epoch: 3,
            broker_revocation_epoch: 4,
            descriptors: vec![ShellV1Descriptor {
                slot: 2,
                generation: 10,
                label: None,
                trust_level: TrustLevel::Isolated,
                attention: AttentionState::Notice,
                action: action(),
            }],
        },
    )
    .unwrap();
    vec![
        ("client_hello", TransactionId::INVALID, hello),
        ("server_welcome", TransactionId::INVALID, welcome),
        ("descriptor_snapshot", transaction, snapshot),
        ("candidate", transaction, candidate),
        ("candidate_reserved", transaction, candidate_reserved),
        ("candidate_hidden", transaction, candidate_hidden),
        ("candidate_outcome", transaction, outcome),
        ("activation", transaction, activation),
        ("activation_ack", transaction, ack),
        (
            "descriptor_snapshot_unlabeled",
            transaction,
            unlabeled_snapshot,
        ),
    ]
}

fn malformed_frames(
    valid: &[(&'static str, TransactionId, Vec<u8>)],
) -> Vec<(&'static str, &'static str, &'static str, Vec<u8>)> {
    let hello = &valid[0].2;
    let welcome = &valid[1].2;
    let snapshot = &valid[2].2;
    let candidate = &valid[3].2;
    let candidate_hidden = &valid[5].2;
    let activation = &valid[7].2;
    let mut cases = Vec::new();
    cases.push((
        "truncated_header",
        "client_hello",
        "truncated",
        hello[..20].to_vec(),
    ));
    let mut frame = hello.clone();
    frame[0] = 0;
    cases.push(("bad_magic", "client_hello", "bad_magic", frame));
    let mut frame = hello.clone();
    frame[4] = 2;
    cases.push((
        "bad_frame_version",
        "client_hello",
        "unsupported_frame_version",
        frame,
    ));
    let mut frame = hello.clone();
    frame[6..8].copy_from_slice(&u16::MAX.to_le_bytes());
    cases.push((
        "unknown_message_kind",
        "client_hello",
        "wrong_message_kind",
        frame,
    ));
    let mut frame = hello.clone();
    frame[16..20].copy_from_slice(&65_537_u32.to_le_bytes());
    cases.push((
        "payload_too_large",
        "client_hello",
        "payload_too_large",
        frame,
    ));
    let mut frame = hello.clone();
    frame[20] = 1;
    cases.push((
        "header_reserved_nonzero",
        "client_hello",
        "reserved_nonzero",
        frame,
    ));
    let mut frame = hello.clone();
    frame.push(0);
    cases.push((
        "trailing_frame_byte",
        "client_hello",
        "trailing_bytes",
        frame,
    ));
    let mut frame = hello.clone();
    frame[8] = 1;
    cases.push((
        "hello_nonzero_transaction",
        "client_hello",
        "invalid_transaction",
        frame,
    ));
    let mut frame = welcome.clone();
    frame[26] = 1;
    cases.push((
        "welcome_reserved_nonzero",
        "server_welcome",
        "reserved_nonzero",
        frame,
    ));
    let mut frame = snapshot.clone();
    frame[8..16].fill(0);
    cases.push((
        "snapshot_zero_transaction",
        "descriptor_snapshot",
        "invalid_transaction",
        frame,
    ));
    // Byte 57 is the reservation edge and bytes 62..64 its thickness; both
    // were reserved-zero before reservations existed, so the zero pattern
    // still decodes as no reservation and these mutations probe the new
    // validation instead of a reserved check.
    let mut frame = candidate.clone();
    frame[57] = 1;
    cases.push((
        "candidate_edge_without_thickness",
        "candidate",
        "invalid_record",
        frame,
    ));
    let mut frame = candidate.clone();
    frame[62..64].copy_from_slice(&28_u16.to_le_bytes());
    cases.push((
        "candidate_thickness_without_edge",
        "candidate",
        "invalid_record",
        frame,
    ));
    let mut frame = candidate.clone();
    frame[57] = 5;
    frame[62..64].copy_from_slice(&28_u16.to_le_bytes());
    cases.push((
        "candidate_unknown_reservation_edge",
        "candidate",
        "invalid_enum",
        frame,
    ));
    let mut frame = candidate.clone();
    frame[57] = 2;
    frame[62..64].copy_from_slice(&513_u16.to_le_bytes());
    cases.push((
        "candidate_reservation_too_thick",
        "candidate",
        "invalid_record",
        frame,
    ));
    let mut frame = candidate_hidden.clone();
    frame[57] = 2;
    frame[62..64].copy_from_slice(&28_u16.to_le_bytes());
    cases.push((
        "candidate_hidden_reservation",
        "candidate",
        "invalid_record",
        frame,
    ));
    let mut frame = activation.clone();
    frame[90] = 1;
    cases.push((
        "activation_reserved_nonzero",
        "activation",
        "reserved_nonzero",
        frame,
    ));
    cases
}

fn action() -> ToplevelActionCapabilityRef {
    ToplevelActionCapabilityRef {
        token: 42,
        issuer_epoch: 3,
        issuer_revocation_epoch: 4,
        recipient_epoch: 5,
        target_slot: 2,
        target_generation: 10,
    }
}

fn hex(bytes: &[u8]) -> String {
    let mut text = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut text, "{byte:02x}").unwrap();
    }
    text
}
