pub mod backend_args;
pub mod backend_evidence;
#[cfg(feature = "atomic-scanout-live")]
pub mod desktop_output_activation;
#[cfg(feature = "atomic-scanout-live")]
pub mod desktop_output_commit;
#[cfg(feature = "atomic-scanout-live")]
pub mod desktop_output_frames;
#[cfg(feature = "atomic-scanout-live")]
pub mod desktop_output_heads;
#[cfg(feature = "atomic-scanout-live")]
pub mod desktop_output_topology;
pub mod desktop_profile_activation;
pub mod emergency_input;
pub mod input_proof;
pub mod native_output_completion;
pub mod resize_transaction;
pub mod session_actions;
pub mod session_control;
pub mod session_keyboard;
pub mod session_shutdown;
pub mod session_startup;
pub mod wm_recovery;
